//! Generates TypeScript bindings (DataView proxies) for Zig `extern struct`s so
//! the frontend can read/write Zig memory.

const std = @import("std");
const app = @import("app");

const Binding = struct { name: []const u8, type: type };

/// The set of structs to emit bindings for: every public `extern struct`
const bindings = collectBindings(app);

fn collectBindings(comptime ns: type) []const Binding {
    var list: []const Binding = &.{};
    inline for (@typeInfo(ns).@"struct".decls) |decl| {
        if (@TypeOf(@field(ns, decl.name)) != type) continue;
        const T = @field(ns, decl.name);
        const info = @typeInfo(T);
        if (info != .@"struct") continue;

        if (info.@"struct".layout == .@"extern") {
            list = list ++ &[_]Binding{.{ .name = decl.name, .type = T }};
        } else if (info.@"struct".fields.len == 0) {
            list = list ++ collectBindings(T);
        }
    }
    return list;
}

pub fn main(init: std.process.Init) !void {
    var args = try init.minimal.args.iterateAllocator(init.gpa);
    defer args.deinit();

    _ = args.next(); // skip executable name
    const out_path = args.next() orelse {
        std.debug.print("usage: gen_ts <output-path>\n", .{});
        return error.MissingOutputPath;
    };

    try std.Io.Dir.cwd().writeFile(init.io, .{
        .sub_path = out_path,
        .data = source,
    });
}

const header =
    \\// AUTO-GENERATED by src/tools/gen_ts.zig — do not edit by hand.
    \\// This entire directory is generated; regenerate with `zig build`.
    \\
    \\
;

/// Shared runtime (type descriptors, layout computation and proxy factory),
const runtime = @embedFile("bindings_runtime.ts");

/// The full generated TypeScript file, built entirely at comptime.
const source = blk: {
    var out: []const u8 = header ++ runtime ++ genTypes();

    for (bindings) |binding| {
        out = out ++ genStruct(binding.type, binding.name);
    }

    const final = out;
    break :blk final;
};

/// Emits one descriptor per distinct Zig type used across all bindings. Size and
/// alignment come from the Zig type system, so the TS side needs no magic widths.
fn genTypes() []const u8 {
    comptime {
        var out: []const u8 = "\n";

        for (usedTypes()) |T| {
            const acc = accessor(T);
            const endian = if (@sizeOf(T) > 1) ", true" else "";

            out = out ++ std.fmt.comptimePrint(
                \\const {[name]s}: ZigType<{[ts]s}> = {{
                \\  size: {[size]d},
                \\  align: {[alignment]d},
                \\  get: (view, offset) => view.get{[method]s}(offset{[endian]s}),
                \\  set: (view, offset, value) => view.set{[method]s}(offset, value{[endian]s}),
                \\}};
                \\
            , .{
                .name = @typeName(T),
                .ts = acc.ts_type,
                .size = @sizeOf(T),
                .alignment = @alignOf(T),
                .method = acc.method,
                .endian = endian,
            });
        }

        return out ++ "\n";
    }
}

/// The distinct field types across all bindings, in first-seen order.
fn usedTypes() []const type {
    comptime {
        var list: []const type = &.{};

        for (bindings) |binding| {
            for (@typeInfo(binding.type).@"struct".fields) |field| {
                var seen = false;
                for (list) |t| {
                    if (t == field.type) seen = true;
                }
                if (!seen) list = list ++ &[_]type{field.type};
            }
        }

        return list;
    }
}

/// Emits the field→type map plus the computed layout, proxy factory and view type.
fn genStruct(comptime T: type, comptime name: []const u8) []const u8 {
    comptime {
        const info = switch (@typeInfo(T)) {
            .@"struct" => |s| s,
            else => @compileError(name ++ " must be a struct"),
        };

        var fields: []const u8 = "";
        for (info.fields) |field| {
            fields = fields ++ std.fmt.comptimePrint(
                "  {s}: {s},\n",
                .{ field.name, @typeName(field.type) },
            );
        }

        return std.fmt.comptimePrint(
            \\const {[name]s}Fields = {{
            \\{[fields]s}}};
            \\
            \\const {[name]s}Computed = computeLayout({[name]s}Fields);
            \\export const {[name]s}Layout = {[name]s}Computed.layout;
            \\export const {[name]s}ByteLength = {[name]s}Computed.byteLength;
            \\
            \\export function create{[name]s}Proxy(view: DataView): Struct<typeof {[name]s}Fields> {{
            \\  return createProxy({[name]s}Fields, {[name]s}Layout, view);
            \\}}
            \\
            \\export type {[name]s}View = ReturnType<typeof create{[name]s}Proxy>;
            \\
            \\
        , .{
            .name = name,
            .fields = fields,
        });
    }
}

const Accessor = struct {
    /// DataView method suffix, e.g. "Int32" -> getInt32/setInt32.
    method: []const u8,
    /// TypeScript type returned/accepted by the accessor.
    ts_type: []const u8,
};

/// Maps a Zig field type to its DataView accessor. Multi-byte values are read/written
/// little-endian (the WASM memory model).
fn accessor(comptime T: type) Accessor {
    return switch (T) {
        bool, u8 => .{ .method = "Uint8", .ts_type = "number" },
        i8 => .{ .method = "Int8", .ts_type = "number" },
        u16 => .{ .method = "Uint16", .ts_type = "number" },
        i16 => .{ .method = "Int16", .ts_type = "number" },
        u32 => .{ .method = "Uint32", .ts_type = "number" },
        i32 => .{ .method = "Int32", .ts_type = "number" },
        f32 => .{ .method = "Float32", .ts_type = "number" },
        f64 => .{ .method = "Float64", .ts_type = "number" },
        u64 => .{ .method = "BigUint64", .ts_type = "bigint" },
        i64 => .{ .method = "BigInt64", .ts_type = "bigint" },
        else => @compileError("unsupported field type for TS bindings: " ++ @typeName(T)),
    };
}
